---
title: "Methodology"
---

In this chapter, the methods employed will be introduces.


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, error = FALSE, message=FALSE, warning=FALSE)
```


```{r}
packages = c('tidytext','widyr','wordcloud','DT','ggwordcloud','textplot','lubridate','hms','tidyverse','tidygraph','ggraph','igraph')
for (p in packages){
  if (!require(p,character.only = T)){
    install.packages(p)
  }
  library(p,character.only = T)
}
```


```{r}
news <- "data/News Articles/"
```


```{r}
read_folder <- function(infolder){
  tibble(file = dir(infolder,
                    full.names = TRUE))%>%
    mutate(text = map(file,
                      read_lines))%>%
    transmute(id = basename(file),
              text)%>%
    unnest(text)
}
```


```{r}
raw_text <- tibble(folder=
                     dir(news,
                         full.names=TRUE)) %>%

  mutate(folder_out = map(folder,read_folder))%>%
  unnest(cols = c(folder_out))%>%
  transmute(newsgroup = basename(folder),
            id,text)
```


```{r}
raw_text %>%
  group_by(newsgroup)%>%
  summarize(messages = n_distinct(id))%>%
  ggplot(aes(messages,newsgroup))+
  geom_col(fill="pink")+
  labs(y=NULL)
```


```{r}
cleaned_text <- raw_text %>%
  group_by(newsgroup, id)%>%
  filter(cumsum(text == "") > 0,
         cumsum(str_detect(
           text, "^--"))==0) %>%
  ungroup()
```



```{r}
cleaned_text <- cleaned_text %>%
  filter(str_detect(text,"^[^>]+[A-Za-z\\d]")
         | text == "",
         !str_detect(text,
                     "writes(:|\\.\\.\\.)$"),
         !str_detect(text,
                     "^In article <")
  )
```



```{r}
usenet_words <- cleaned_text %>%
  unnest_tokens(word, text) %>%
  filter(str_detect(word, "[a-z']$"),
         !word %in% stop_words$word)
```



```{r}
usenet_words %>%
  count(word, sort = TRUE)
```


```{r}
words_by_newsgroup <- usenet_words%>%
  count(newsgroup, word, sort = TRUE) %>%
  ungroup()
```



```{r}
wordcloud(words_by_newsgroup$word,
          words_by_newsgroup$n,
          max.words = 400)
```


```{r}
set.seed(1234)

words_by_newsgroup %>%
  filter(n > 0)%>%
ggplot (aes(label = word,
              size = n)) +
  geom_text_wordcloud() +
  theme_minimal() +
  facet_wrap(~newsgroup)
```



```{r}
tf_idf <- words_by_newsgroup %>%
  bind_tf_idf (word, newsgroup, n) %>%
  arrange(desc(tf_idf)) 
```



```{r}
DT::datatable(tf_idf, filter = 'top') %>%
  formatRound(columns = c('tf', 'idf',
                          'tf_idf'),
              digits = 3) %>%
  formatStyle(0,
              target = 'row',
              lineHeight='35%')
```



```{r}
newsgroup_cors <- words_by_newsgroup %>%
  pairwise_cor (newsgroup,
                word,
                n,
                sort = TRUE)
```



```{r}
set.seed(2017)

newsgroup_cors %>%
  filter(correlation > .025) %>%
  graph_from_data_frame() %>%
  ggraph(layout = "fr") +
  geom_edge_link(aes(alpha = correlation,
                     width = correlation)) +
  geom_node_point(size = 6,
                  color = "red") +
  geom_node_text(aes(label = name),
                 color = "darkorange",
                 repel = TRUE) +
  theme_void()
```



```{r}
bigrams <- cleaned_text %>%
  unnest_tokens(bigram,
                text,
                token = "ngrams",
                n=2)
```



```{r}
bigrams_count <- bigrams %>%
  filter(bigram != 'NA') %>%
  count(bigram, sort = TRUE)

bigrams_count
```


```{r}
bigrams_separated <- bigrams %>%
  filter(bigram != 'NA') %>%
  separate(bigram, c("word1", "word2"),
           sep = " ")

bigrams_filtered <- bigrams_separated %>%
  filter(!word1 %in% stop_words$word) %>%
  filter(!word2 %in% stop_words$word)

bigrams_filtered
```


```{r}
bigram_counts <- bigrams_filtered %>%
  count(word1, word2, sort = TRUE)
```



```{r}
bigram_graph <- bigram_counts %>%
  filter (n > 3) %>%
  graph_from_data_frame()
bigram_graph
```


```{r}
set.seed(1234)

ggraph(bigram_graph, layout = "fr") +
  geom_edge_link() +
  geom_node_point() +
  geom_node_text(aes(label = name),
                 vjust = 1,
                 hjust = 1)
```


```{r}
set.seed(1234)

a <- grid::arrow(type = "closed",
                 length = unit(.15, "inches"))

ggraph(bigram_graph, 
       layout = "fr") +
  geom_edge_link(aes(edge_alpha = n),
                 show.legend = FALSE,
                 arrow = a,
                 end_cap = circle (.07, 'inches')) +
  geom_node_point(color = "lightblue",
                  sizze = 5) +
  geom_node_text(aes(label = name),
                 vjust = 1,
                 hjust = 1)
theme_void()
```

